### ISSUE TITLE
Combine all of the above and make a calculator

### ISSUE THREAD

**Issue by JoyenBenitto** [acmpesuecc/8085--Assembly-instructions#2]
Take input of 1,2,3 or 4 in a register  and  based on the I/P ADD, SUB, MUL and DIV and save the result.

**Comment by Harshit-crypto** [comment]
can i work on issue 1 @JoyenBenitto

**Comment by Harshit-crypto** [comment]
can i work on this issue @JoyenBenitto

**Comment by JoyenBenitto** [comment]
@Harshit-crypto  sure you can work !!!!

**Comment by surajkadapa** [comment]
@JoyenBenitto Please assign me to this

**Comment by NityaShukla0** [comment]
Please assign this to me
